//! Cross-platform determinism check. CI runs this on every target triple (Windows x64,
//! macOS arm64/x64, Linux x64/arm64); every one must produce exactly these hashes.
//!
//! If you changed the generator on purpose: bump `GEN_VERSION`, then regenerate the table
//! with `cargo run -p rvgen-cli -- golden` and paste it below.

use rvgen::hash::Fnv64;
use rvgen::{ChunkCoord, SeedCode, World, scatter};

/// (seed code, chunk, terrain hash, trees hash, props hash)
type Golden = (&'static str, (i32, i32), u64, u64, u64);

// Generated by `cargo run -p rvgen-cli -- golden` on linux-x86_64.
#[rustfmt::skip]
const EXPECTED: &[Golden] = &[
    ("DT6-00000-0000M", (0, 0), 0xd12d9c3612f09f86, 0x03f31e17928b4272, 0x0bbe4ede37206a45),
    ("DT6-00000-0000M", (1, -1), 0x58af6d83b62a0bdc, 0x9688c70acbbe7ad4, 0xf8997bfce44df62b),
    ("DT6-00000-0000M", (-5, 3), 0x5ec202c7ed704714, 0xf1f84ceb24796824, 0x57b06b06ef9d9745),
    ("DT6-00000-0000M", (40, -80), 0x111337c9a3d474b2, 0x97de38e9e1dc3535, 0xca6e4bba45feb743),
    ("DT6-80005-BSQQN", (0, 0), 0xe537c76235c48932, 0x9cf03bccb803af96, 0x2707731ed002c2c5),
    ("DT6-80005-BSQQN", (1, -1), 0x4984a614ca3ab743, 0xbc435985951839c4, 0xde254c66e302e2d9),
    ("DT6-80005-BSQQN", (-5, 3), 0x370c118912f51910, 0xb8880a274e1fbdd0, 0x0e0339da520bada2),
    ("DT6-80005-BSQQN", (40, -80), 0x6bc40700e2c70128, 0x7b6eb0eed0a2cdf8, 0xdefea7e45942aeee),
    ("DT6-GFZZZ-ZZZZJ", (0, 0), 0x95e575ffcf7aa4ab, 0x1f869869714a136d, 0x971465674a241ef5),
    ("DT6-GFZZZ-ZZZZJ", (1, -1), 0x12afb30eb0d6579d, 0x7ba3596c7f13e637, 0x64b001846f11a016),
    ("DT6-GFZZZ-ZZZZJ", (-5, 3), 0x98427f59cdf2af8f, 0x71a9919c23f923a4, 0x82d2cc58d5800c52),
    ("DT6-GFZZZ-ZZZZJ", (40, -80), 0x6ecf9f00d954876f, 0xac327caf03341ec9, 0xd4860d4225c718c2),
];

fn props_hash(world: &World, coord: ChunkCoord) -> u64 {
    let hf = world.heightfield(coord);
    let trees = scatter::trees(world, &hf);
    let mut h = Fnv64::new();
    for p in scatter::props(world, &hf, &trees) {
        for v in [
            p.pos[0], p.pos[1], p.pos[2], p.up[0], p.up[1], p.up[2], p.yaw, p.scale,
        ] {
            h.write(&v.to_bits().to_le_bytes());
        }
        h.write(&[p.kind as u8, p.variant]);
    }
    h.finish()
}

fn trees_hash(world: &World, coord: ChunkCoord) -> u64 {
    let hf = world.heightfield(coord);
    let mut h = Fnv64::new();
    for t in scatter::trees(world, &hf) {
        for v in [t.pos[0], t.pos[1], t.pos[2], t.yaw, t.scale] {
            h.write(&v.to_bits().to_le_bytes());
        }
        h.write(&[t.kind]);
    }
    h.finish()
}

#[test]
fn golden_hashes_match() {
    let mut failures = Vec::new();
    for &(code, (cx, cz), terrain, trees, props) in EXPECTED {
        let world = World::new(SeedCode::parse(code).unwrap()).unwrap();
        let c = ChunkCoord::new(cx, cz);
        let got_terrain = world.heightfield(c).content_hash();
        let got_trees = trees_hash(&world, c);
        let got_props = props_hash(&world, c);
        if got_terrain != terrain || got_trees != trees || got_props != props {
            failures.push(format!(
                "{code} chunk ({cx},{cz}): terrain {got_terrain:016x} (want {terrain:016x}), \
                 trees {got_trees:016x} (want {trees:016x}), props {got_props:016x} (want {props:016x})"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "world generation differs on {}-{}:\n{}",
        std::env::consts::OS,
        std::env::consts::ARCH,
        failures.join("\n")
    );
}
