//! Cross-platform determinism check. CI runs this on every target triple (Windows x64,
//! macOS arm64/x64, Linux x64/arm64); every one must produce exactly these hashes.
//!
//! If you changed the generator on purpose: bump `GEN_VERSION`, then regenerate the table
//! with `cargo run -p rvgen-cli -- golden` and paste it below.

use rvgen::hash::Fnv64;
use rvgen::{ChunkCoord, SeedCode, World, scatter};

/// (seed code, chunk, terrain hash, trees hash, props hash)
type Golden = (&'static str, (i32, i32), u64, u64, u64);

// Generated by `cargo run -p rvgen-cli -- golden` on macos-aarch64.
const EXPECTED: &[Golden] = &[
    (
        "DT1-00000-0000N",
        (0, 0),
        0x7585ca9ee9cd7632,
        0x839d975213b3e7cb,
        0xf46ea543ca455dc6,
    ),
    (
        "DT1-00000-0000N",
        (1, -1),
        0xf1688c3861273d62,
        0x34035e7c2149b628,
        0xecfacdd9cff5662f,
    ),
    (
        "DT1-00000-0000N",
        (-5, 3),
        0xa814fc883dc0ee5f,
        0x93880a2da63f9384,
        0x4ef28ed2aef37bc6,
    ),
    (
        "DT1-00000-0000N",
        (40, -80),
        0x07a3579c1d54074d,
        0xdf4a369707497c15,
        0xf7371b77f179a3d2,
    ),
    (
        "DT1-80005-BSQQM",
        (0, 0),
        0x9c51e8854c4ee20d,
        0x9ee02a87fdad18c7,
        0x20ff0e8918ade4f2,
    ),
    (
        "DT1-80005-BSQQM",
        (1, -1),
        0x1f0a2c2f9df5ef62,
        0xaf1b750949355a6c,
        0x69e93851181e5006,
    ),
    (
        "DT1-80005-BSQQM",
        (-5, 3),
        0x488f33a3728214a6,
        0x5bbce3775686a21f,
        0xce81d3bf042eb109,
    ),
    (
        "DT1-80005-BSQQM",
        (40, -80),
        0xa33ca0f6331376a9,
        0x18ae67a3e1b76e31,
        0xc6a41cae846a50b1,
    ),
    (
        "DT1-GFZZZ-ZZZZK",
        (0, 0),
        0xf3185b723c5d14db,
        0xefbc3b17ed2af7dc,
        0x077362344833edcb,
    ),
    (
        "DT1-GFZZZ-ZZZZK",
        (1, -1),
        0x0e35369c95c55023,
        0x8ff0a139255fcfd6,
        0x28b61545fc61587e,
    ),
    (
        "DT1-GFZZZ-ZZZZK",
        (-5, 3),
        0x284da2d9ed7b2124,
        0x0970c7bb95e7b18f,
        0x5fe0839a294f4105,
    ),
    (
        "DT1-GFZZZ-ZZZZK",
        (40, -80),
        0x9a21ac465f19d101,
        0x09e11fa0d16b2fe7,
        0x29c62fd6a0ac19a9,
    ),
];

fn props_hash(world: &World, coord: ChunkCoord) -> u64 {
    let hf = world.heightfield(coord);
    let trees = scatter::trees(world, &hf);
    let mut h = Fnv64::new();
    for p in scatter::props(world, &hf, &trees) {
        for v in [
            p.pos[0], p.pos[1], p.pos[2], p.up[0], p.up[1], p.up[2], p.yaw, p.scale,
        ] {
            h.write(&v.to_bits().to_le_bytes());
        }
        h.write(&[p.kind as u8, p.variant]);
    }
    h.finish()
}

fn trees_hash(world: &World, coord: ChunkCoord) -> u64 {
    let hf = world.heightfield(coord);
    let mut h = Fnv64::new();
    for t in scatter::trees(world, &hf) {
        for v in [t.pos[0], t.pos[1], t.pos[2], t.yaw, t.scale] {
            h.write(&v.to_bits().to_le_bytes());
        }
        h.write(&[t.kind]);
    }
    h.finish()
}

#[test]
fn golden_hashes_match() {
    let mut failures = Vec::new();
    for &(code, (cx, cz), terrain, trees, props) in EXPECTED {
        let world = World::new(SeedCode::parse(code).unwrap()).unwrap();
        let c = ChunkCoord::new(cx, cz);
        let got_terrain = world.heightfield(c).content_hash();
        let got_trees = trees_hash(&world, c);
        let got_props = props_hash(&world, c);
        if got_terrain != terrain || got_trees != trees || got_props != props {
            failures.push(format!(
                "{code} chunk ({cx},{cz}): terrain {got_terrain:016x} (want {terrain:016x}), \
                 trees {got_trees:016x} (want {trees:016x}), props {got_props:016x} (want {props:016x})"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "world generation differs on {}-{}:\n{}",
        std::env::consts::OS,
        std::env::consts::ARCH,
        failures.join("\n")
    );
}
