//! Cross-platform determinism check. CI runs this on every target triple (Windows x64,
//! macOS arm64/x64, Linux x64/arm64); every one must produce exactly these hashes.
//!
//! If you changed the generator on purpose: bump `GEN_VERSION`, then regenerate the table
//! with `cargo run -p rvgen-cli -- golden` and paste it below.

use rvgen::hash::Fnv64;
use rvgen::{ChunkCoord, SeedCode, World, scatter};

/// (seed code, chunk, terrain hash, trees hash, props hash)
type Golden = (&'static str, (i32, i32), u64, u64, u64);

// Generated by `cargo run -p rvgen-cli -- golden` on macos-aarch64.
#[rustfmt::skip]
const EXPECTED: &[Golden] = &[
    ("DT3-00000-0000S", (0, 0), 0x928d683e79a48a2b, 0xae2039f6359f0028, 0x241d4376b4e0ce9f),
    ("DT3-00000-0000S", (1, -1), 0xa15940be59f40b30, 0xbbf3af0e72a6804c, 0x6ba11be829e07ac7),
    ("DT3-00000-0000S", (-5, 3), 0x0909482dcb090241, 0x7f1ff1e12437a4e2, 0x4ecfe51cbdd3eaec),
    ("DT3-00000-0000S", (40, -80), 0xdc72c2e78c8d2e8f, 0xa59932fda8023e31, 0xb017b02814acdcad),
    ("DT3-80005-BSQQR", (0, 0), 0x7c936c7e4ebeacd5, 0xcf1924d13a6d20bc, 0x2aa167bb2cbd18dc),
    ("DT3-80005-BSQQR", (1, -1), 0x32541abdef393e90, 0x088976c47e6691ad, 0xe803a81b8a251340),
    ("DT3-80005-BSQQR", (-5, 3), 0x9e971778c26a6424, 0x9cd4ec61c2693df5, 0xce81d3bf042eb109),
    ("DT3-80005-BSQQR", (40, -80), 0xe7d11ba4c1af1105, 0x7b6eb0eed0a2cdf8, 0xdefea7e45942aeee),
    ("DT3-GFZZZ-ZZZZZ", (0, 0), 0xf277b90976be9ba0, 0x072ec7e540d7d8b2, 0x19a26672b5681ae8),
    ("DT3-GFZZZ-ZZZZZ", (1, -1), 0x4f44de031534bd9d, 0x6a7c443e8cfc83d5, 0xfb95c0765f9c8b3c),
    ("DT3-GFZZZ-ZZZZZ", (-5, 3), 0x950c9954f4a91a76, 0x71a9919c23f923a4, 0x82d2cc58d5800c52),
    ("DT3-GFZZZ-ZZZZZ", (40, -80), 0xeecefcea0969d5ba, 0xac327caf03341ec9, 0xd4860d4225c718c2),
];

fn props_hash(world: &World, coord: ChunkCoord) -> u64 {
    let hf = world.heightfield(coord);
    let trees = scatter::trees(world, &hf);
    let mut h = Fnv64::new();
    for p in scatter::props(world, &hf, &trees) {
        for v in [
            p.pos[0], p.pos[1], p.pos[2], p.up[0], p.up[1], p.up[2], p.yaw, p.scale,
        ] {
            h.write(&v.to_bits().to_le_bytes());
        }
        h.write(&[p.kind as u8, p.variant]);
    }
    h.finish()
}

fn trees_hash(world: &World, coord: ChunkCoord) -> u64 {
    let hf = world.heightfield(coord);
    let mut h = Fnv64::new();
    for t in scatter::trees(world, &hf) {
        for v in [t.pos[0], t.pos[1], t.pos[2], t.yaw, t.scale] {
            h.write(&v.to_bits().to_le_bytes());
        }
        h.write(&[t.kind]);
    }
    h.finish()
}

#[test]
fn golden_hashes_match() {
    let mut failures = Vec::new();
    for &(code, (cx, cz), terrain, trees, props) in EXPECTED {
        let world = World::new(SeedCode::parse(code).unwrap()).unwrap();
        let c = ChunkCoord::new(cx, cz);
        let got_terrain = world.heightfield(c).content_hash();
        let got_trees = trees_hash(&world, c);
        let got_props = props_hash(&world, c);
        if got_terrain != terrain || got_trees != trees || got_props != props {
            failures.push(format!(
                "{code} chunk ({cx},{cz}): terrain {got_terrain:016x} (want {terrain:016x}), \
                 trees {got_trees:016x} (want {trees:016x}), props {got_props:016x} (want {props:016x})"
            ));
        }
    }
    assert!(
        failures.is_empty(),
        "world generation differs on {}-{}:\n{}",
        std::env::consts::OS,
        std::env::consts::ARCH,
        failures.join("\n")
    );
}
